apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-app-demo
  namespace: helm-app-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "5.2.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    ui:
      color: "#34577c"
    service:
      enabled: true
      type: LoadBalancer
