apiVersion: v1
kind: Namespace
metadata:
  name: addon-y
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-y
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argais/podinfo.git
    targetRevision: HEAD
    path: charts/podinfo
    helm:
      # releaseName: mypodinfo
      parameters:
      - name: ui.color
        value: "#bbccdd"
      values: |
        ui:
          message: "hello world :)"
  destination:
    server: https://kubernetes.default.svc
    namespace: addon-y
